basePath: /api/v1
definitions:
  main.ApiAddFirmwareInfoRequest:
    properties:
      boards:
        items:
          type: string
        minItems: 1
        type: array
      built_at:
        type: integer
      commit_id:
        type: string
      description:
        type: string
      repo_name:
        type: string
      sha256:
        type: string
    required:
    - boards
    - built_at
    - commit_id
    - repo_name
    type: object
  main.ApiAddFirmwareRequest:
    properties:
      bin_base64:
        type: string
      info:
        $ref: '#/definitions/main.ApiAddFirmwareInfoRequest'
    required:
    - bin_base64
    - info
    type: object
  main.ApiFirmwareInfoResponse:
    properties:
      boards:
        items:
          type: string
        type: array
      built_at:
        type: integer
      commit_id:
        type: string
      description:
        type: string
      id:
        type: integer
      loaded_at:
        type: integer
      loaded_by:
        type: string
      repo_name:
        type: string
      sha256:
        type: string
      size:
        type: integer
    type: object
  main.ApiFirmwareResponse:
    properties:
      bin_url:
        type: string
      info:
        $ref: '#/definitions/main.ApiFirmwareInfoResponse'
    type: object
  main.HttpError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: OTA server
  version: "1.0"
paths:
  /bin/{id}:
    get:
      description: Get binary firmware file with given id. Available for all authenticated
        users
      parameters:
      - description: firmware's ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: file
        "401":
          description: Invalid auth token
          schema:
            $ref: '#/definitions/main.HttpError'
        "404":
          description: firmware not found
          schema:
            $ref: '#/definitions/main.HttpError'
      security:
      - ApiKeyAuth: []
      summary: Get binary file
  /firmwares:
    get:
      description: Get all firmwares. Only for non-board users
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/main.ApiFirmwareResponse'
            type: array
        "401":
          description: Invalid auth token
          schema:
            $ref: '#/definitions/main.HttpError'
        "403":
          description: Access is denied
          schema:
            $ref: '#/definitions/main.HttpError'
      security:
      - ApiKeyAuth: []
      summary: Get all firmwares
    post:
      consumes:
      - application/json
      description: Get all firmwares. Only for non-board users
      parameters:
      - description: firmware info and binary
        in: body
        name: firmware
        required: true
        schema:
          $ref: '#/definitions/main.ApiAddFirmwareRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/main.ApiFirmwareResponse'
        "401":
          description: Invalid auth token
          schema:
            $ref: '#/definitions/main.HttpError'
        "403":
          description: Access is denied
          schema:
            $ref: '#/definitions/main.HttpError'
      security:
      - ApiKeyAuth: []
      summary: Add firmware information and binary
  /firmwares/latest:
    get:
      description: Get latest firmware version for given repo and tags. Only for boards
      parameters:
      - description: name of firmware's repo
        in: query
        name: repo
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/main.ApiFirmwareResponse'
        "401":
          description: Invalid auth token
          schema:
            $ref: '#/definitions/main.HttpError'
        "403":
          description: Access is denied
          schema:
            $ref: '#/definitions/main.HttpError'
        "404":
          description: no firmware found for this board in repo
          schema:
            $ref: '#/definitions/main.HttpError'
      security:
      - ApiKeyAuth: []
      summary: Get latest firmware version
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Token
    type: apiKey
swagger: "2.0"
